[package]
name = "gravity_proto_build"
version = "0.1.0"
authors = ["Justin Kilpatrick <justin@althea.net>"]
edition = "2018"


[dependencies]
prost = { workspace = true }
tonic = { workspace = true }
prost-build = "0.7"
tempdir = "0.3"
walkdir = "2"
tonic-build = "0.4"
regex = "1.5"
