[package]
name = "gravity_proto_build"
version = "0.2.0"
authors = ["Justin Kilpatrick <justin@althea.net>"]
edition = "2018"


[dependencies]
prost = "0.11"
tonic = "0.8"
prost-build = "0.11"
tempdir = "0.3"
walkdir = "2"
tonic-build = "0.8"
regex = "1.6"
