[package]
name = "somm_ethereum_gravity"
version = "0.1.0"
authors = ["PeggyJV <info@peggy.cool>, Justin Kilpatrick <justin@althea.net>"]
edition = "2018"
description = "This is a library that contains code for the interactions with the counterparty ethereum chain."
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
somm_gravity_utils = {version = "0.1.0", path = "../gravity_utils"}
deep_space = {version = "2.4.3", git="https://github.com/iqlusioninc/deep_space/", branch="zaki/tendermint_0_21"}
clarity = "0.4.11"
web30 = "0.14.4"
num256 = "0.3"
log = "0.4"
sha3 = "0.9"
