keystore = "/tmp/keystore"

[gravity]
contract = "0x6b175474e89094c44da98b954eedeac495271d0f"
fees_denom = "stake"

[ethereum]
key_derivation_path = "m/44'/60'/0'/0/0"
rpc = "http://localhost:8545"

[cosmos]
gas_price = { amount = 0.001, denom = "stake" }
grpc = "http://localhost:9090"
key_derivation_path = "m/44'/118'/0'/0/0"
prefix = "cosmos"

[metrics]
listen_addr = "127.0.0.1:3000"
