[package]
name = "cosmos_register_delegate_keys"
version = "0.1.0"
authors = ["PeggyJV <info@peggy.cool>, Justin Kilpatrick <justin@althea.net>"]
edition = "2018"
description = "This is a binary for running a command to register delegate keys for a validatore"
license = "Apache-2.0"

[[bin]]
name = "cosmos_register-delegate-keys"
path = "src/main.rs"

[dependencies]
cosmos_relayer = { version = "0.1.1", path = "../relayer" }
cosmos_ethereum_gravity = { version = "0.1.0", path = "../ethereum_gravity" }
cosmos_gravity = { version = "0.1.0", path = "../cosmos_gravity" }
cosmos_gravity_utils = { version = "0.1.0", path = "../gravity_utils" }
cosmos_gravity_proto = { version = "0.1.2", path = "../gravity_proto" }

deep_space = { version = "2.4.3", git = "https://github.com/iqlusioninc/deep_space/", branch = "zaki/tendermint_0_21" }
contact = "0.4"
serde_derive = "1.0"
clarity = "0.4.11"
docopt = "1"
serde = "1.0"
actix-rt = "2.2.0"
lazy_static = "1"
web30 = "0.14.4"
env_logger = "0.8"
log = "0.4.14"
openssl-probe = "0.1"
rand = "0.8"
