[package]
name = "cosmos_gravity_test_runner"
version = "0.1.0"
authors = ["PeggyJV <info@peggy.cool>, Justin Kilpatrick <justin@althea.net>"]
edition = "2018"
description = "This is a binary which runs tests against a cosmos chain"
license = "Apache-2.0"

# only becuase I like - more in names
[[bin]]
name = "test_runner"
path = "src/main.rs"

[dependencies]
cosmos_ethereum_gravity = { version = "0.1.0", path = "../ethereum_gravity" }
cosmos_gravity = { version = "0.1.0", path = "../cosmos_gravity" }
cosmos_gravity_utils = { version = "0.1.0", path = "../gravity_utils" }
cosmos_gravity_proto = { version = "0.1.2", path = "../gravity_proto/" }
cosmos_orchestrator = { version = "0.1.0", path = "../orchestrator" }

deep_space = { version = "2.4.3", git = "https://github.com/iqlusioninc/deep_space/", branch = "zaki/tendermint_0_21" }
serde_derive = "1.0"
clarity = "0.4.11"
docopt = "1"
serde = "1.0"
actix = "0.11"
actix-web = { version = "3", features = ["openssl"] }
actix-rt = "2.2"
lazy_static = "1"
url = "2"
web30 = "0.14.4"
num256 = "0.3"
log = "0.4"
env_logger = "0.8"
tokio = "1.4.0"
rand = "0.8"
tonic = "0.4"
futures = "0.3"
