[package]
name = "somm_cosmos_gravity"
version = "0.1.0"
authors = ["PeggyJV <info@peggy.cool>, Justin Kilpatrick <justin@althea.net>"]
edition = "2018"
description = "This is a library for interacting with the cosmos chain both queries and transactions. It substantally wraps gravity_proto."
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
somm_gravity_utils = {version = "0.1.0", path = "../gravity_utils"}
somm_ethereum_gravity = {version = "0.1.0", path = "../ethereum_gravity"}
somm_gravity_proto = {version = "0.1.1", path = "../gravity_proto/"}

deep_space ={version = "2.4.3", git="https://github.com/iqlusioninc/deep_space/", branch="zaki/tendermint_0_21"}
clarity = "0.4.11"
serde = "1.0"
num256 = "0.3"
log = "0.4"
sha3 = "0.9"
tokio = "1.4"
web30 = "0.14.4"
tonic = "0.4"
cosmos-sdk-proto = "0.6.1"
prost = "0.7"
prost-types = "0.7"
bytes = "1"

[dev-dependencies]
env_logger = "0.8"
rand = "0.8"
actix = "0.11"