name: Go tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  go-test:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Create Go cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('module/go.sum') }}
      - name: Run Go tests
        run: cd module && make test-cov
          #      - uses: codecov/codecov-action@v2
          #        with:
          #          token: ${{ secrets.CODECOV_TOKEN }}
          #          file: ./module/coverage.txt
          #          fail_ci_if_error: true
